package com.web.model;
// Generated 13-mag-2018 22.29.48 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IduserIdfileId generated by hbm2java
 */
@Embeddable
public class IduserIdfileId  implements java.io.Serializable {


     private long userId;
     private long fileCod;

    public IduserIdfileId() {
    }

    public IduserIdfileId(long userId, long fileCod) {
       this.userId = userId;
       this.fileCod = fileCod;
    }
   


    @Column(name="userId", nullable=false)
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }


    @Column(name="fileCod", nullable=false)
    public long getFileCod() {
        return this.fileCod;
    }
    
    public void setFileCod(long fileCod) {
        this.fileCod = fileCod;
    }




}


