package com.web.model;
// Generated 13-mag-2018 22.29.48 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name="persona"
    ,catalog="test"
)
public class Persona  implements java.io.Serializable {


     private Long id;
     private String codfiscale;
     private String cog;
     private Integer eta;
     private String nome;

    public Persona() {
    }

    public Persona(String codfiscale, String cog, Integer eta, String nome) {
       this.codfiscale = codfiscale;
       this.cog = cog;
       this.eta = eta;
       this.nome = nome;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="CODFISCALE")
    public String getCodfiscale() {
        return this.codfiscale;
    }
    
    public void setCodfiscale(String codfiscale) {
        this.codfiscale = codfiscale;
    }

    
    @Column(name="COG")
    public String getCog() {
        return this.cog;
    }
    
    public void setCog(String cog) {
        this.cog = cog;
    }

    
    @Column(name="ETA")
    public Integer getEta() {
        return this.eta;
    }
    
    public void setEta(Integer eta) {
        this.eta = eta;
    }

    
    @Column(name="NOME")
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }




}


