package com.web.model;
// Generated 13-mag-2018 22.29.48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ruolo generated by hbm2java
 */
@Entity
@Table(name="ruolo_"
    ,catalog="test"
)
public class Ruolo  implements java.io.Serializable {


     private Long id;
     private String ruolo;
     private Set<User> users = new HashSet<User>(0);

    public Ruolo() {
    }

    public Ruolo(String ruolo, Set<User> users) {
       this.ruolo = ruolo;
       this.users = users;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_", nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="ruolo_")
    public String getRuolo() {
        return this.ruolo;
    }
    
    public void setRuolo(String ruolo) {
        this.ruolo = ruolo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ruolo")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


