package com.web.model;
// Generated 13-mag-2018 22.29.48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="test"
)
public class User  implements java.io.Serializable {


     private Long id;
     private Ruolo ruolo;
     private String email;
     private String password;
     private Set<IduserIdfile> iduserIdfiles = new HashSet<IduserIdfile>(0);

    public User() {
    }

    public User(Ruolo ruolo, String email, String password, Set<IduserIdfile> iduserIdfiles) {
       this.ruolo = ruolo;
       this.email = email;
       this.password = password;
       this.iduserIdfiles = iduserIdfiles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_")
    public Ruolo getRuolo() {
        return this.ruolo;
    }
    
    public void setRuolo(Ruolo ruolo) {
        this.ruolo = ruolo;
    }

    
    @Column(name="email")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password")
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<IduserIdfile> getIduserIdfiles() {
        return this.iduserIdfiles;
    }
    
    public void setIduserIdfiles(Set<IduserIdfile> iduserIdfiles) {
        this.iduserIdfiles = iduserIdfiles;
    }




}


